task: ViT
synthesizer: Pattern

data_path: '../fundus_dataset/'

batch_size: 32
test_batch_size: 48
attack: True
lr: 0.00015
momentum: 0.9
decay: 0.0
epochs: 100
save_on_epochs: []
optimizer: Adam
log_interval: 100

scheduler: True
pretrained: True
amp: False
max_batch_id: 1000

poisoning_proportion: 0.05
backdoor_label: 4.0
backdoor: True

loss_balance: fixed
mgda_normalize: loss+

save_model: True
log: True
tb: True

transform_train: True


loss_tasks:
  - backdoor
  - normal